import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";
import { drizzle } from "drizzle-orm/postgres-js";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import postgres from "postgres";
import { PRIMARY_KEY_COLUMN } from "@/constants";

/**
 * Generates an OpenAPI-compliant CRUD router for a database table
 *
 * @param tableName - Name of the database table
 * @param table - Runtime-generated Drizzle table schema
 * @param connectionString - PostgreSQL connection string
 * @returns OpenAPIHono router with CRUD endpoints
 */
export function createCrudRouter(
  tableName: string,
  // biome-ignore lint/suspicious/noExplicitAny: Runtime-generated table schemas require dynamic typing
  table: any,
  connectionString: string
): OpenAPIHono {
  const app = new OpenAPIHono();

  // Auto-generate Zod schemas
  // Type assertion needed due to drizzle-zod and @hono/zod-openapi version compatibility
  const selectSchema = createSelectSchema(table) as unknown as z.ZodTypeAny;
  // Make id optional for insert (it's auto-generated by the database)
  const baseInsertSchema = createInsertSchema(table);
  const insertSchema = baseInsertSchema.omit({
    [PRIMARY_KEY_COLUMN]: true,
  }) as unknown as z.ZodTypeAny;

  // GET / (List)
  app.openapi(
    createRoute({
      method: "get",
      path: "/",
      tags: [tableName],
      responses: {
        200: {
          content: { "application/json": { schema: z.array(selectSchema) } },
          description: "List",
        },
      },
    }),
    async (c) => {
      const client = postgres(connectionString);
      const db = drizzle(client);
      try {
        const results = await db.select().from(table);
        return c.json(results);
      } finally {
        await client.end();
      }
    }
  );

  // POST / (Create)
  app.openapi(
    createRoute({
      method: "post",
      path: "/",
      tags: [tableName],
      request: {
        body: { content: { "application/json": { schema: insertSchema } } },
      },
      responses: { 201: { description: "Created" } },
    }),
    async (c) => {
      const client = postgres(connectionString);
      const db = drizzle(client);
      try {
        const body = await c.req.json();
        const result = await db.insert(table).values(body).returning();
        if (result.length === 0) {
          return c.json({ error: "Insert failed" }, 500);
        }
        return c.json(result[0], 201);
      } finally {
        await client.end();
      }
    }
  );

  return app;
}
